import { Component, OnInit, inject, DestroyRef, TransferState, makeStateKey, PLATFORM_ID, RESPONSE_INIT } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { HttpClient, HttpParams } from '@angular/common/http';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { getLocalizedTitle } from '../shared/utils/listing-locale';
import { HeaderComponent } from '../shared/components/header/header.component';
import { ReportModalComponent } from '../shared/components/report-modal/report-modal.component';
import { AuthService } from '../auth/services/auth.service';
import { FollowService, FollowStatus } from '../shared/services/follow.service';
import { API_CONFIG } from '../shared/config/api.config';
import { applySsrStatus } from '../shared/utils/ssr-status';

export interface PublicReview {
  _id: string;
  score: number;
  tags: string[];
  role: 'as_seller' | 'as_buyer';
  isAutoGenerated: boolean;
  createdAt: string;
  reviewer: { firstName: string; lastInitial: string } | null;
}

interface PublicProfile {
  _id: string;
  slug: string | null;
  firstName: string;
  lastName: string;
  memberSince: string;
  lastActive: string | null;
  sellerScore: number | null;
  sellerReviewCount: number;
  buyerScore: number | null;
  buyerReviewCount: number;
  soldCount: number;
  boughtCount: number;
  followersCount: number;
  activeListings: {
    _id: string;
    slug: string;
    title: string;
    titlePt?: string | null;
    titleEn?: string | null;
    images: string[];
    currentPrice: number;
    startingPrice: number;
    bidCount: number;
    endDate: string;
    auctionFormat: string;
  }[];
}

type ReviewSort = 'recent' | 'highest' | 'lowest';
type ReviewRole = 'all' | 'as_seller' | 'as_buyer';
type Tab = 'listings' | 'reviews';

@Component({
  selector: 'app-seller-public-profile',
  standalone: true,
  imports: [CommonModule, RouterLink, TranslateModule, HeaderComponent, ReportModalComponent],
  templateUrl: './seller-public-profile.component.html',
  styleUrls: ['./seller-public-profile.component.scss']
})
export class SellerPublicProfileComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private http = inject(HttpClient);
  private authService = inject(AuthService);
  private followService = inject(FollowService);
  private translate = inject(TranslateService);
  private transferState = inject(TransferState);
  private isBrowser = isPlatformBrowser(inject(PLATFORM_ID));
  private destroyRef = inject(DestroyRef);
  private responseInit = inject(RESPONSE_INIT, { optional: true });

  private apiBase = API_CONFIG.getApiUrl();

  profile: PublicProfile | null = null;
  loading = true;
  error: string | null = null;
  showReportModal = false;
  isAuthenticated = false;
  isSelf = false;

  followStatus: FollowStatus = { following: false, muted: false };
  followLoading = false;

  // Tabs
  activeTab: Tab = 'listings';

  // Reviews
  reviews: PublicReview[] = [];
  reviewsLoading = false;
  reviewsError = false;
  reviewSort: ReviewSort = 'recent';
  reviewRoleFilter: ReviewRole = 'all';
  reviewPage = 1;
  reviewPages = 1;
  reviewTotal = 0;

  listingTitle(listing: { title: string; titlePt?: string | null; titleEn?: string | null }): string {
    return getLocalizedTitle(listing, this.translate.currentLang || 'pt');
  }

  ngOnInit(): void {
    this.authService.isAuthenticated().pipe(takeUntilDestroyed(this.destroyRef)).subscribe(auth => {
      this.isAuthenticated = auth;
    });

    const id = this.route.snapshot.paramMap.get('id');
    if (!id) {
      this.error = 'Invalid profile URL.';
      this.loading = false;
      applySsrStatus(this.responseInit, 404);
      return;
    }

    this.authService.currentUser$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(user => {
      if (user && this.profile) {
        this.isSelf = user.uid === this.profile._id || false;
      }
    });

    const stateKey = makeStateKey<PublicProfile | null>(`seller-profile:${id}`);
    const cached = this.transferState.get(stateKey, null);

    if (cached) {
      this.transferState.remove(stateKey);
      this.profile = cached;
      this.loading = false;
      this.checkSelf();
      if (this.isAuthenticated && !this.isSelf) {
        this.loadFollowStatus(cached._id);
      }
      return;
    }

    this.http.get<PublicProfile>(`${this.apiBase}/users/${id}/profile`).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: (profile) => {
        if (!this.isBrowser) {
          this.transferState.set(stateKey, profile);
        }
        this.profile = profile;
        this.loading = false;
        this.checkSelf();
        if (this.isAuthenticated && !this.isSelf) {
          this.loadFollowStatus(profile._id);
        }
      },
      error: (err) => {
        this.error = err.status === 404 ? 'sellerProfile.notFound' : 'sellerProfile.loadError';
        this.loading = false;
        if (err.status === 404) applySsrStatus(this.responseInit, 404);
      }
    });
  }

  switchTab(tab: Tab): void {
    this.activeTab = tab;
    if (tab === 'reviews' && this.reviews.length === 0 && !this.reviewsLoading) {
      this.loadReviews();
    }
  }

  loadReviews(page = 1): void {
    if (!this.profile) return;
    this.reviewsLoading = true;
    this.reviewsError = false;
    this.reviewPage = page;

    let params = new HttpParams()
      .set('sort', this.reviewSort)
      .set('page', String(page));

    if (this.reviewRoleFilter !== 'all') {
      params = params.set('role', this.reviewRoleFilter);
    }

    this.http.get<{ reviews: PublicReview[]; total: number; pages: number }>(
      `${this.apiBase}/users/${this.profile._id}/reviews`, { params }
    ).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: (res) => {
        this.reviews = res.reviews;
        this.reviewTotal = res.total;
        this.reviewPages = res.pages;
        this.reviewsLoading = false;
      },
      error: () => {
        this.reviewsError = true;
        this.reviewsLoading = false;
      }
    });
  }

  setReviewSort(sort: ReviewSort): void {
    if (this.reviewSort === sort) return;
    this.reviewSort = sort;
    this.loadReviews(1);
  }

  setReviewRoleFilter(role: ReviewRole): void {
    if (this.reviewRoleFilter === role) return;
    this.reviewRoleFilter = role;
    this.loadReviews(1);
  }

  private checkSelf(): void {
    const user = this.authService.getCurrentUser();
    if (user && this.profile) {
      this.isSelf = user.uid === this.profile._id;
    }
  }

  private loadFollowStatus(sellerId: string): void {
    this.followService.getStatus(sellerId).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: (status) => { this.followStatus = status; },
      error: () => {}
    });
  }

  toggleFollow(): void {
    if (!this.profile || this.followLoading) return;
    this.followLoading = true;
    const action = this.followStatus.following
      ? this.followService.unfollow(this.profile._id)
      : this.followService.follow(this.profile._id);

    action.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: (status) => { this.followStatus = status; this.followLoading = false; },
      error: () => { this.followLoading = false; }
    });
  }

  toggleMute(): void {
    if (!this.profile || this.followLoading) return;
    this.followLoading = true;
    this.followService.setMuted(this.profile._id, !this.followStatus.muted).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: (status) => { this.followStatus = status; this.followLoading = false; },
      error: () => { this.followLoading = false; }
    });
  }

  starsArray(score: number): number[] {
    return Array.from({ length: 5 }, (_, i) => i + 1);
  }

  formatTag(tag: string): string {
    return tag.replace(/_/g, ' ');
  }

  isPositiveTag(tag: string): boolean {
    const positive = ['fast_payment', 'fast_shipping', 'item_as_described', 'great_packaging',
      'good_communication', 'smooth_transaction', 'trustworthy'];
    return positive.includes(tag);
  }

  formatPrice(price: number): string {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'EUR' }).format(price);
  }

  memberSinceYear(): string {
    if (!this.profile?.memberSince) return '';
    return new Date(this.profile.memberSince).getFullYear().toString();
  }

  formatLastActive(date: string | null): string {
    if (!date) return 'sellerProfile.lastActiveUnknown';
    const diff = Date.now() - new Date(date).getTime();
    const mins = Math.floor(diff / 60000);
    if (mins < 5) return 'sellerProfile.lastActiveNow';
    if (mins < 60) return `${mins}m ago`;
    const hrs = Math.floor(mins / 60);
    if (hrs < 24) return `${hrs}h ago`;
    const days = Math.floor(hrs / 24);
    if (days < 30) return `${days}d ago`;
    return new Date(date).toLocaleDateString();
  }

  displayName(): string {
    if (!this.profile) return '';
    const last = this.profile.lastName ? ` ${this.profile.lastName.charAt(0)}.` : '';
    return `${this.profile.firstName}${last}`;
  }

  timeRemaining(endDate: string): string {
    const diff = new Date(endDate).getTime() - Date.now();
    if (diff <= 0) return 'Ended';
    const days = Math.floor(diff / 86400000);
    const hours = Math.floor((diff % 86400000) / 3600000);
    if (days > 0) return `${days}d ${hours}h`;
    const mins = Math.floor((diff % 3600000) / 60000);
    return `${hours}h ${mins}m`;
  }

  get totalReviewCount(): number {
    return (this.profile?.sellerReviewCount ?? 0) + (this.profile?.buyerReviewCount ?? 0);
  }

  get overallScore(): number | null {
    const ss = this.profile?.sellerScore;
    const bs = this.profile?.buyerScore;
    const sc = this.profile?.sellerReviewCount ?? 0;
    const bc = this.profile?.buyerReviewCount ?? 0;
    if (!ss && !bs) return null;
    // if (!bs) return ss;
    // if (!ss) return bs;
    // const weighted = (ss * sc + bs * bc) / (sc + bc);
    const weighted = (ss ?? 0) * (sc ?? 0) + (bs ?? 0) * (bc ?? 0);
    return Math.round(weighted * 10) / 10;
  }
}
