const mongoose = require('mongoose');

/**
 * Review - one user reviewing another after a completed transaction.
 * reviewer: User who wrote the review
 * reviewee: User being reviewed (the "reviewed" party)
 * role: 'as_buyer' = reviewee is being reviewed as buyer (reviewer was seller)
 *       'as_seller' = reviewee is being reviewed as seller (reviewer was buyer)
 * score: 1-5 (visible to all; used for aggregations)
 * description: optional text (private - never returned to other users)
 */
const reviewSchema = new mongoose.Schema({
  listing: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Listing',
    required: true,
    index: true
  },
  reviewer: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Customer',
    required: false,
    default: null,
    index: true
  },
  reviewee: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Customer',
    required: true,
    index: true
  },
  role: {
    type: String,
    enum: ['as_buyer', 'as_seller'],
    required: true,
    index: true
  },
  /** Score 1-5 (visible publicly) */
  score: {
    type: Number,
    required: true,
    min: 1,
    max: 5,
    index: true
  },
  /** Review description text (private - never exposed to other users) */
  description: {
    type: String,
    maxlength: 2000,
    default: null,
    trim: true
  },
  /** Completion date of the reviewed transaction (for 30-day review window audits) */
  transactionCompletedAt: {
    type: Date,
    default: null
  },
  /**
   * HMAC-SHA256 of the reviewer's IP at submission time (not the raw IP).
   * Stored as a salted hash so the IP-cluster heuristic still works (equality on
   * deterministic hashes) while keeping the original IP out of the database.
   */
  reviewerIp: {
    type: String,
    trim: true,
    default: null
  },
  reviewerUserAgent: {
    type: String,
    trim: true,
    maxlength: 500,
    default: null
  },
  /** Predefined experience tags selected by the reviewer (max 5) */
  tags: {
    type: [String],
    enum: [
      'fast_payment', 'fast_shipping', 'item_as_described', 'great_packaging',
      'good_communication', 'smooth_transaction', 'trustworthy',
      'slow_payment', 'slow_shipping', 'not_as_described', 'poor_communication',
      'non_payment'
    ],
    default: []
  },
  /** True when created automatically by the scheduler after the 5-day window */
  isAutoGenerated: {
    type: Boolean,
    default: false,
    index: true
  },
  /** True when issued by the BidRoom platform (e.g. non-payment penalty) */
  isPlatformReview: {
    type: Boolean,
    default: false,
    index: true
  }
}, {
  timestamps: true,
  collection: 'reviews'
});

// One review per (listing, reviewer, reviewee) - seller reviews buyer once, buyer reviews seller once
reviewSchema.index({ listing: 1, reviewer: 1, reviewee: 1 }, { unique: true });
reviewSchema.index({ reviewee: 1, role: 1 }); // For aggregating scores by reviewee

const Review = mongoose.model('Review', reviewSchema);

module.exports = Review;
