/**
 * Review Auto-Generate Scheduler
 *
 * Runs every 6 hours. After 5 days from a terminal transaction state
 * (completed or cancelled), if a review hasn't been submitted between
 * the two parties, the system automatically creates a 5-star review
 * on their behalf — keeping score counts healthy and protecting both
 * parties from silence being penalised.
 */

const Transaction = require('../models/Transaction');
const Review = require('../models/Review');
const Customer = require('../models/Customer');

const LOG_PREFIX = '[ReviewAutoGenerate]';
const AUTO_REVIEW_DAYS = 5;
const AUTO_REVIEW_MS = AUTO_REVIEW_DAYS * 24 * 60 * 60 * 1000;
const BATCH_LIMIT = 500;
const TERMINAL_STATUSES = ['completed', 'cancelled'];

let _timer = null;

function startReviewAutoGenerateScheduler(intervalHours = 6, io = null) {
  if (_timer) return;
  const ms = intervalHours * 60 * 60 * 1000;
  // Initial run 2 minutes after startup
  setTimeout(() => runAutoGenerate(io).catch(e => console.error(LOG_PREFIX, 'startup:', e.message)), 2 * 60 * 1000);
  _timer = setInterval(() => runAutoGenerate(io).catch(e => console.error(LOG_PREFIX, 'interval:', e.message)), ms);
  console.log(`${LOG_PREFIX} Scheduler started (every ${intervalHours}h, auto-review after ${AUTO_REVIEW_DAYS} days).`);
}

function stopReviewAutoGenerateScheduler() {
  if (_timer) { clearInterval(_timer); _timer = null; }
}

async function runAutoGenerate(io) {
  const cutoff = new Date(Date.now() - AUTO_REVIEW_MS);

  // Find transactions past the 5-day window that haven't been auto-reviewed yet
  const transactions = await Transaction.find({
    transactionStatus: { $in: TERMINAL_STATUSES },
    // completedAt covers 'completed'; updatedAt is the fallback for 'cancelled'
    $or: [
      { completedAt: { $lte: cutoff } },
      { completedAt: null, updatedAt: { $lte: cutoff } }
    ],
    seller: { $exists: true },
    buyer: { $exists: true },
    listing: { $exists: true }
  })
    .select('_id listing seller buyer transactionStatus completedAt updatedAt')
    .limit(BATCH_LIMIT)
    .lean();

  if (transactions.length === 0) return;

  // Batch-load all existing reviews for these listings to avoid N+1
  const listingIds = [...new Set(transactions.map(t => t.listing?.toString()).filter(Boolean))];
  const existingReviews = await Review.find({
    listing: { $in: listingIds }
  }).select('listing reviewer reviewee isAutoGenerated').lean();

  const reviewedKeys = new Set(
    existingReviews.map(r => `${r.listing}-${r.reviewer}-${r.reviewee}`)
  );

  let created = 0;

  for (const tx of transactions) {
    const lid = tx.listing?.toString();
    const buyerId = tx.buyer?.toString();
    const sellerId = tx.seller?.toString();
    if (!lid || !buyerId || !sellerId) continue;

    const pairs = [
      // buyer → seller (role: as_seller means the reviewee is being reviewed as seller)
      { reviewerId: buyerId, revieweeId: sellerId, role: 'as_seller' },
      // seller → buyer (role: as_buyer means the reviewee is being reviewed as buyer)
      { reviewerId: sellerId, revieweeId: buyerId, role: 'as_buyer' }
    ];

    for (const { reviewerId, revieweeId, role } of pairs) {
      const key = `${lid}-${reviewerId}-${revieweeId}`;
      if (reviewedKeys.has(key)) continue;

      try {
        await Review.create({
          listing: tx.listing,
          reviewer: reviewerId,
          reviewee: revieweeId,
          role,
          score: 5,
          description: null,
          tags: [],
          transactionCompletedAt: tx.completedAt || tx.updatedAt,
          isAutoGenerated: true
        });
        reviewedKeys.add(key); // prevent duplicate on next pair in same loop
        created++;
      } catch (err) {
        if (err.code !== 11000) {
          console.error(LOG_PREFIX, `Failed to create auto-review for tx ${tx._id}:`, err.message);
        }
      }
    }
  }

  if (created > 0) {
    console.log(`${LOG_PREFIX} Auto-generated ${created} reviews for ${transactions.length} transactions.`);
  }
}

module.exports = { startReviewAutoGenerateScheduler, stopReviewAutoGenerateScheduler };
