export const environment = {
  production: true,
  appUrl: 'https://blue-glacier-0e23ae710.2.azurestaticapps.net/landing',
  enableAuctions: false,
  enablePrivateRooms: false,
  enableBestOffers: true,
  apiUrl: 'https://bidroom-backend-dev.azurewebsites.net/api',
  defaultApiBaseUrl: 'https://bidroom-backend-dev.azurewebsites.net/api',
  auctionDurations: [
    { label: '5 minutes', hours: 1 / 12 },
    { label: '1 hour', hours: 1 },
    { label: '7 hours', hours: 7 },
    { label: '24 hours', hours: 24 },
  ],
  title: 'Casa 27 | E2E',
  description: 'Casa 27 | E2E. Compre e venda ao melhor preço',
  keywords: 'Casa 27, E2E, Compre e venda ao melhor preço',
  author: 'Casa 27',
  creator: 'Casa 27',
  publisher: 'Casa 27 | E2E',
  url: 'https://casa27.com/e2e',
  image: 'https://casa27.com/api/public/image.png',
  imageAlt: 'Casa 27 | E2E',
  primaryColor: '#1988c5',
  shippingOptions: [
    { label: 'Flat Rate', value: 'flat-rate' },
    { label: 'Calculated', value: 'calculated' },
    { label: 'Local Pickup', value: 'local-pickup' },
    { label: 'Free', value: 'free' },
  ],
  handlingTimes: [
    { label: '1 day', value: 1 },
    { label: '2 days', value: 2 },
    { label: '3 days', value: 3 },
    { label: '5 days', value: 5 },
    { label: '7 days', value: 7 },
  ],
  returnPolicies: [
    { label: '30 days', value: '30-days' },
    { label: '14 days', value: '14-days' },
    { label: 'No Returns', value: 'no-returns' },
    { label: 'Custom', value: 'custom' },
  ],
  bidroomFeeSellerRate: 0.005,
  bidroomFeeBuyerRate: 0.005,
};
