export const environment = {
  production: true,
  googleAnalyticsId: 'G-4FDFR1ZSRV',
  posthog: {
    apiKey:  'phc_kLcVSTdnMKj4eDek9zMhTKGxsqvtFTrYyVUhQxXRRwgh',
    apiHost: 'https://us.i.posthog.com',
    enabled: true,
  },
  appUrl: 'https://calm-desert-0d6601f10.1.azurestaticapps.net',
  enableAuctions: false,
  enablePrivateRooms: false,
  enableBestOffers: true,
  apiUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api',
  defaultApiBaseUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api',
  firebase: {
    apiKey: 'AIzaSyBb3nk50nwBME8dN5pNhu2W1B7-m35qqHw',
    authDomain: 'bidroom-47cb5.firebaseapp.com',
    projectId: 'bidroom-47cb5',
    storageBucket: 'bidroom-47cb5.firebasestorage.app',
    messagingSenderId: '16761692806',
    appId: '1:16761692806:web:b1e10f2a57a040f8556707',
    measurementId: 'G-4FDFR1ZSRV',
  },
  auctionDurations: [
    { label: '1 hour', hours: 1 },
    { label: '7 hours', hours: 7 },
    { label: '24 hours', hours: 24 },
  ],
  title: 'BidRoom Portugal',
  description: 'Casa 27. Compre e venda ao melhor preço',
  keywords: 'Casa 27, Compre e venda ao melhor preço',
  author: 'Casa 27',
  creator: 'Casa 27',
  publisher: 'Casa 27',
  url: 'https://casa27.com',
  image: 'https://casa27.com/api/public/image.png',
  imageAlt: 'Casa 27',
  primaryColor: '#002366',
  secondaryColor: '#00D4FF',
  backgroundColor: '#F8FAFC',
  shippingOptions: [
    { label: 'Flat Rate', value: 'flat-rate' },
    { label: 'Calculated', value: 'calculated' },
    { label: 'Local Pickup', value: 'local-pickup' },
    { label: 'Free', value: 'free' },
  ],
  handlingTimes: [
    { label: '1 day', value: 1 },
    { label: '2 days', value: 2 },
    { label: '3 days', value: 3 },
    { label: '5 days', value: 5 },
    { label: '7 days', value: 7 },
  ],
  returnPolicies: [
    { label: '30 days', value: '30-days' },
    { label: '14 days', value: '14-days' },
    { label: 'No Returns', value: 'no-returns' },
    { label: 'Custom', value: 'custom' },
  ],
  bidroomFeeSellerRate: 0.005,
  bidroomFeeBuyerRate: 0.005,
  featureFlags: {
    auctions: false,
    privateRooms: false,
    bestOffers: true,
    reviews: true,
    membershipTiers: false,
  },
  theme: {
    primaryColor: '#002366',
    secondaryColor: '#00D4FF',
    backgroundColor: '#F8FAFC',
  },
};
