export const environment = {
  production: true,
  auctionDurations: [
    { label: '1 hour',   hours: 1  },
    { label: '7 hours',  hours: 7  },
    { label: '24 hours', hours: 24 },
  ],
  enableAuctions: true,
  enablePrivateRooms: true,
  enableBestOffers: true,
  logoUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/logo.png',
  faviconUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/favicon.ico',
  appleTouchIconUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/apple-touch-icon.png',
  manifestUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/manifest.json',
  twitterCardUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/twitter-card.png',
  facebookImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/facebook-image.png',
  instagramImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/instagram-image.png',
  linkedinImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/linkedin-image.png',
  youtubeImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/youtube-image.png',
  tiktokImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/tiktok-image.png',
  pinterestImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/pinterest-image.png',
  redditImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/reddit-image.png',
  discordImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/discord-image.png',
  telegramImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/telegram-image.png',
  whatsappImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/whatsapp-image.png',
  snapchatImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/snapchat-image.png',
  vimeoImageUrl: 'https://bidroom-backend-dev.azurewebsites.net/api/public/vimeo-image.png',
  title: 'Casa 27', 
  description: 'Casa 27. Compre e venda ao melhor preço',
  keywords: 'Casa 27, Compre e venda ao melhor preço',
  author: 'Casa 27',
  creator: 'Casa 27',
  publisher: 'Casa 27',
  url: 'https://casa27.com',
  image: 'https://casa27.com/api/public/image.png',
  imageAlt: 'Casa 27',
};
