export const environment = {
  production: true,
  title: 'BidRoom Portugal',
  description: 'House 27. Compre e venda ao melhor preço',
  keywords: 'House 27, Compre e venda ao melhor preço',
  author: 'House 27',
  creator: 'House 27',
  publisher: 'House 27',
  url: 'https://house27.com',
  image: 'https://house27.com/api/public/image.png',
  imageAlt: 'House 27',
  /** When APP_CONFIG.API_URL is not injected — set to your production API base */
  defaultApiBaseUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api',
  auctionDurations: [
    { label: '5 minutes', hours: 1 / 12 },
    { label: '1 hour',   hours: 1  },
    { label: '7 hours',  hours: 7  },
    { label: '24 hours', hours: 24 },
  ],
  primaryColor: '#002366',
  secondaryColor: '#00D4FF',
  backgroundColor: '#F8FAFC',
  enableAuctions: true,
  enablePrivateRooms: true,
  enableBestOffers: true,
  logoUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/logo.png',
  faviconUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/favicon.ico',
  appleTouchIconUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/apple-touch-icon.png',
  manifestUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/manifest.json',
  twitterCardUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/twitter-card.png',
  facebookImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/facebook-image.png',
  instagramImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/instagram-image.png',
  linkedinImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/linkedin-image.png',
  youtubeImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/youtube-image.png',
  tiktokImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/tiktok-image.png',
  pinterestImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/pinterest-image.png',
  redditImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/reddit-image.png',
  discordImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/discord-image.png',
  telegramImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/telegram-image.png',
  whatsappImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/whatsapp-image.png',
  snapchatImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/snapchat-image.png',
  vimeoImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/vimeo-image.png',
  shippingOptions: [
    { label: 'Flat Rate', value: 'flat-rate' },
    { label: 'Calculated', value: 'calculated' },
    { label: 'Local Pickup', value: 'local-pickup' },
    { label: 'Free', value: 'free' },
  ],
  handlingTimes: [
    { label: '1 day', value: 1 },
    { label: '2 days', value: 2 },
    { label: '3 days', value: 3 },
    { label: '5 days', value: 5 },
    { label: '7 days', value: 7 },
  ],
  returnPolicies: [
    { label: '30 days', value: '30-days' },
    { label: '14 days', value: '14-days' },
    { label: 'No Returns', value: 'no-returns' },
    { label: 'Custom', value: 'custom' },
  ],
  /** Seller commission rate (0.005 = 0.5%, 0.02 = 2% for private room) */
  bidroomFeeSellerRate: 0.005,
  /** Buyer fee rate (0.005 = 0.5%, 0.05 = 5%) */
  bidroomFeeBuyerRate: 0.005,
};
