export const environment = {
  production: false,
  title: 'BidRoom',
  enableAuctions: true,
  enablePrivateRooms: true,
  enableBestOffers: true,
  /** When APP_CONFIG.API_URL is not injected, non-localhost builds use this API base */
  defaultApiBaseUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api',
  /** Seller fee: 3.5% for auctions & best-offer, 6% for private-room auctions */
  bidroomFeeSellerRate: 0.035,
  bidroomFeePrivateRoomRate: 0.06,
  /** Buyer pays Stripe processing fees only — no additional BidRoom buyer fee */
  bidroomFeeBuyerRate: 0,
  auctionDurations: [
    { label: '5 minutes', hours: 1 / 12 },
    { label: '1 hour',    hours: 1      },
    { label: '7 hours',   hours: 7      },
    { label: '24 hours',  hours: 24     },
  ],
  primaryColor: '#8b5a96',
  secondaryColor: '#00D4FF',
  backgroundColor: '#F8FAFC',
  logoUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/logo.png',
  faviconUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/favicon.ico',
  appleTouchIconUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/apple-touch-icon.png',
  manifestUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/manifest.json',
  twitterCardUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/twitter-card.png',
  facebookImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/facebook-image.png',
  instagramImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/instagram-image.png',
  linkedinImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/linkedin-image.png',
  youtubeImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/youtube-image.png',
  tiktokImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/tiktok-image.png',
  pinterestImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/pinterest-image.png',
  redditImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/reddit-image.png',
  discordImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/discord-image.png',
  telegramImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/telegram-image.png',
  whatsappImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/whatsapp-image.png',
  snapchatImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/snapchat-image.png',
  vimeoImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/vimeo-image.png',
};
