export const environment = {
  production: true,
  title: 'BidRoom Portugal',
  description: 'House 27. Compre e venda ao melhor preço',
  keywords: 'House 27, Compre e venda ao melhor preço',
  author: 'House 27',
  creator: 'House 27',
  publisher: 'House 27',
  url: 'https://house27.com',
  image: 'https://house27.com/api/public/image.png',
  imageAlt: 'House 27',
  defaultApiBaseUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api',
  firebase: {
    apiKey: 'AIzaSyBb3nk50nwBME8dN5pNhu2W1B7-m35qqHw',
    authDomain: 'bidroom-47cb5.firebaseapp.com',
    projectId: 'bidroom-47cb5',
    storageBucket: 'bidroom-47cb5.firebasestorage.app',
    messagingSenderId: '16761692806',
    appId: '1:16761692806:web:b1e10f2a57a040f8556707',
    measurementId: 'G-4FDFR1ZSRV',
  },
  /** Seller fee: 3.5% for auctions & best-offer, 6% for private-room auctions */
  bidroomFeeSellerRate: 0.035,
  bidroomFeePrivateRoomRate: 0.06,
  /** Buyer pays Stripe processing fees only — no additional BidRoom buyer fee */
  bidroomFeeBuyerRate: 0,
  auctionDurations: [
    { label: '5 minutes', hours: 1 / 12 },
    { label: '1 hour',   hours: 1  },
    { label: '7 hours',  hours: 7  },
    { label: '24 hours', hours: 24 },
  ],
  primaryColor: '#002366',
  secondaryColor: '#00D4FF',
  backgroundColor: '#F8FAFC',
  enableAuctions: true,
  enablePrivateRooms: true,
  enableBestOffers: true,
  logoUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/logo.png',
  faviconUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/favicon.ico',
  appleTouchIconUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/apple-touch-icon.png',
  manifestUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/manifest.json',
  twitterCardUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/twitter-card.png',
  facebookImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/facebook-image.png',
  instagramImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/instagram-image.png',
  linkedinImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/linkedin-image.png',
  youtubeImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/youtube-image.png',
  tiktokImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/tiktok-image.png',
  pinterestImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/pinterest-image.png',
  redditImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/reddit-image.png',
  discordImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/discord-image.png',
  telegramImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/telegram-image.png',
  whatsappImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/whatsapp-image.png',
  snapchatImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/snapchat-image.png',
  vimeoImageUrl: 'https://bidroom-backend-prod-e9eghtc0aha4e3dw.uksouth-01.azurewebsites.net/api/public/vimeo-image.png',
  shippingOptions: [
    { label: 'Flat Rate',      value: 'flat-rate'    },
    { label: 'Calculated',     value: 'calculated'   },
    { label: 'Meet in Person', value: 'local-pickup' },
    { label: 'Free',           value: 'free'         },
  ],
  handlingTimes: [
    { label: '1 day',  value: 1 },
    { label: '2 days', value: 2 },
    { label: '3 days', value: 3 },
    { label: '5 days', value: 5 },
    { label: '7 days', value: 7 },
  ],
  returnPolicies: [
    { label: '30 days',    value: '30-days'    },
    { label: '14 days',    value: '14-days'    },
    { label: 'No Returns', value: 'no-returns' },
    { label: 'Custom',     value: 'custom'     },
  ],
  featureFlags: {
    auctions:        true,
    privateRooms:    true,
    bestOffers:      true,
    reviews:         true,
    membershipTiers: false,
  },
  theme: {
    primaryColor:    '#002366',
    secondaryColor:  '#00D4FF',
    backgroundColor: '#F8FAFC',
  },
};
